### ISSUE TITLE
Configurar restablecimiento de contraseña

### ISSUE THREAD

**Issue by ISCLuisRamirez** [ISCLuisRamirez/ArcosaPlus2.0#1]
Configurar restablecimiento de contraseña con cuenta de TI

Puedes seguir este video tutorial para hacerlo funcionar en local.
https://www.youtube.com/watch?v=g5Zpaa2xM7Q

**Comment by erickavila15** [comment]
@ISCLuisRamirez me trabe en una parte del proceso, en donde supuestamente deberia llevarme al reetablecimiento de la contraseña, pero a la hora de darle al boton para restablecer me dice que no existe el vinculo
