### ISSUE TITLE
Crear Modelo Customers

### ISSUE THREAD

**Issue by ISCLuisRamirez** [ISCLuisRamirez/ArcosaPlus2.0#13]
Migración:
            $table->bigIncrements('id');
            $table->string('tradeName')->nullable();
            $table->string('businessName')->nullable();
            $table->string('rfc')->nullable();
            $table->string('address')->nullable();
            $table->string('extNumber')->nullable();
            $table->string('intNumber')->nullable();
            $table->string('colony')->nullable();
            $table->string('postalCode')->nullable();
            $table->string('municipality')->nullable();
            $table->string('state')->nullable();
            $table->string('country')->nullable();
            $table->string('googleMaps')->nullable();
            $table->char('status',1)->default('1');
            $table->timestamps();

Modelo:
protected $fillable = ['tradeName','businessName','rfc','address','extNumber','intNumber','colony','postalCode','municipality','state','country','googleMaps','status','credit','cash'];

    public function getRouteKeyName()
    {
        return 'id';
    }

**Comment by ISCLuisRamirez** [comment]
@erickavila15 

![image](https://user-images.githubusercontent.com/44370473/86186580-129e1c00-baff-11ea-9c8e-a062432fed22.png)

**Comment by erickavila15** [comment]
@ISCLuisRamirez  Approved
![image](https://user-images.githubusercontent.com/58272782/86297116-bb0fb700-bbb7-11ea-9464-4634d6e0de8e.png)
