### ISSUE TITLE
Crear Modelo Types

### ISSUE THREAD

**Issue by ISCLuisRamirez** [ISCLuisRamirez/ArcosaPlus2.0#14]
Migración:
            $table->bigIncrements('id');
            $table->string('name');
            $table->char('status',1)->default('1');
            $table->timestamps();

Modelo:
    protected $fillable = ['name','status'];

    public function getRouteKeyName()
    {
        return 'id';
    }

    public function categories(){
        return $this->hasMany('App\Category');
    }

**Comment by ISCLuisRamirez** [comment]
@erickavila15 
![image](https://user-images.githubusercontent.com/44370473/86187200-db306f00-bb00-11ea-9fd2-92fd7d0bfcd6.png)

**Comment by erickavila15** [comment]
@ISCLuisRamirez  Approved 
![image](https://user-images.githubusercontent.com/58272782/86297194-ee524600-bbb7-11ea-90ef-53437b23b7ea.png)
