### ISSUE TITLE
Crear Modelo Category

### ISSUE THREAD

**Issue by ISCLuisRamirez** [ISCLuisRamirez/ArcosaPlus2.0#15]
Migración:
            $table->bigIncrements('id');
            $table->Integer('type_id')->unsigned();
            $table->string('name');
            $table->char('status',1)->default('1');
            $table->timestamps();

Modelo:
    protected $fillable = ['name','type_id','status'];

    public function getRouteKeyName()
    {
        return 'id';
    }

    public function types(){
        return $this->belongsTo('App\Type');
    }

**Comment by erickavila15** [comment]
@ISCLuisRamirez Approved 
![image](https://user-images.githubusercontent.com/58272782/86297275-18a40380-bbb8-11ea-9e7e-9aebe9a5010e.png)
