### ISSUE TITLE
Agregar Roles a Seeder

### ISSUE THREAD

**Issue by ISCLuisRamirez** [ISCLuisRamirez/ArcosaPlus2.0#19]
Crear roles en seeder:

- AdminModule
- MaintenanceModule
- ProductionModule
- SalesModule

**Comment by erickavila15** [comment]
@ISCLuisRamirez approved
![prueba develop](https://user-images.githubusercontent.com/58272782/85906420-db183280-b7d3-11ea-8a6d-4ac6b8ed52bd.png)
