### ISSUE TITLE
Hacer imágenes default de Arcosa Plus azules.

### ISSUE THREAD

**Issue by erickavila15** [ISCLuisRamirez/ArcosaPlus2.0#22]
cambiar las imágenes de color rojo a color azul en el Layout 
![imagenes 1](https://user-images.githubusercontent.com/58272782/85908153-8f688780-b7d9-11ea-9680-248d396b1b69.png)

![image](https://user-images.githubusercontent.com/58272782/85908176-ab6c2900-b7d9-11ea-9404-ea4cb7495e79.png)

![image](https://user-images.githubusercontent.com/58272782/85908186-b6bf5480-b7d9-11ea-89ea-895af7838fe8.png)

**Comment by ISCLuisRamirez** [comment]
![image](https://user-images.githubusercontent.com/44370473/85908832-65fd2b00-b7dc-11ea-99a0-6af7ecbf16cd.png)

**Comment by erickavila15** [comment]
@ISCLuisRamirez Approved 
![image](https://user-images.githubusercontent.com/58272782/86186361-209b6f00-baf6-11ea-81b3-3fbb6836d430.png)
![image](https://user-images.githubusercontent.com/58272782/86186392-34df6c00-baf6-11ea-9cc5-aa79460152c0.png)
![image](https://user-images.githubusercontent.com/58272782/86186407-4294f180-baf6-11ea-8d43-c9a1042acd2a.png)
