### ISSUE TITLE
Imagen default user

### ISSUE THREAD

**Issue by ISCLuisRamirez** [ISCLuisRamirez/ArcosaPlus2.0#25]
Agregar ruta para imagen por default encapsulada

![image](https://user-images.githubusercontent.com/44370473/86185317-abcb3380-bafb-11ea-9d44-f6463b2a2410.png)

![image](https://user-images.githubusercontent.com/44370473/86185287-97873680-bafb-11ea-8281-35633090c90e.png)

Agregar variable con ruta en appservicesprovider 'DEFAULT_USER_IMAGE'

**Comment by erickavila15** [comment]
@ISCLuisRamirez  @erickavila15  approved 
![image](https://user-images.githubusercontent.com/58272782/86293678-5bfa7400-bbb0-11ea-9a55-dd0a973ad1a1.png)
