### ISSUE TITLE
crear migracion customer_user

### ISSUE THREAD

**Issue by ISCLuisRamirez** [ISCLuisRamirez/ArcosaPlus2.0#26]
Migracion:
            $table->bigIncrements('id');
            $table->Integer('customer_id')->unsigned();
            $table->Integer('user_id)->unsigned();
            $table->timestamps();

**Saber que usuario creo el cliente**

**Comment by erickavila15** [comment]
@ISCLuisRamirez Approved 
![image](https://user-images.githubusercontent.com/58272782/86297345-4c7f2900-bbb8-11ea-9b3f-0eab2f364db7.png)
