### ISSUE TITLE
Vista, controlador y ruta Types

### ISSUE THREAD

**Issue by ISCLuisRamirez** [ISCLuisRamirez/ArcosaPlus2.0#27]
Crear controlador TypesController (resource)
Rutas para controlador (resource)
Vista index.blade.php

**Comment by erickavila15** [comment]
@ISCLuisRamirez Approved
![image](https://user-images.githubusercontent.com/58272782/86412973-5454d100-bc7d-11ea-9ecb-ab31724a1cdc.png)
![image](https://user-images.githubusercontent.com/58272782/86413007-69316480-bc7d-11ea-92e5-00d495390ddf.png)
![image](https://user-images.githubusercontent.com/58272782/86413061-89612380-bc7d-11ea-8273-a6d9f16d6434.png)
